### ISSUE TITLE
studio.exe launch problem in Win10

### ISSUE THREAD

**Issue by godshow** [nem0/LumixEngine#1014]
It will crash with message `Bin directory not found, please check working directory`, when launch from studio.exe directly.
If i launch studio.exe from VS IDE , it will not crash.
I have set the working directory correctly.

**Comment by nem0** [comment]
Hi, use the shortcut LumixStudio.lnk from the root directory

**Comment by nem0** [comment]
Is it still a problem?

**Comment by godshow** [comment]
@nem0 
Thanks.
studio.exe in lumixengine_data/bin is a prebuilt file, not exported by myself.
At last, i copy all files in lumixengine_data to LumixEngine,it's OK.

**Comment by nem0** [comment]
If you build the engine in Visual Studio, you can just set working directory to lumixengine_data, no need to copy anything. If you use prebuilt binaries, just start ```LumixStudio.lnk```.
https://github.com/nem0/LumixEngine/wiki/Getting-started

**Comment by godshow** [comment]
@nem0 
I see.
