### ISSUE TITLE
Clouds

### ISSUE THREAD

**Issue by nem0** [nem0/LumixEngine#1028]

**Comment by nem0** [comment]
https://github.com/JakubLukas/LumixCloudSystem

**Comment by HeadClot** [comment]
YAY Clouds!

Got to ask tho - Are these volumetric?

Just curious :)

**Comment by nem0** [comment]
@HeadClot Not made by me, but I think the simulation is volumetric, so I guess rendering can be volumetric too.

**Comment by HeadClot** [comment]
Thanks for the reply @nem0 :)

Good to know.

**Comment by JakubLukas** [comment]
It will be volumetric, If I ever finish it :D

**Comment by nem0** [comment]
https://github.com/nem0/LumixEngine/wiki/Available-plugins

**Comment by nem0** [comment]
http://bitsquid.blogspot.com/2016/07/volumetric-clouds.html

**Comment by nem0** [comment]
Part of atmosphere shader for now https://github.com/nem0/LumixEngine/blob/master/data/shaders/atmo.hlsl. It needs to be optimized - noise from texture and temporal accumulation.
