### ISSUE TITLE
FBX Import Issue

### ISSUE THREAD

**Issue by nem0** [nem0/LumixEngine#1096]
[default_pose_char+wep.zip](https://github.com/nem0/LumixEngine/files/743215/default_pose_char.wep.zip)

**Comment by nem0** [comment]
Caused by https://github.com/assimp/assimp/issues/1127, LumixEngine's plugin using FBX SDK https://github.com/nem0/lumixengine_fbx do not have this problem

**Comment by mesilliac** [comment]
(should now be fixed in assimp master)

**Comment by nem0** [comment]
@mesilliac thanks, but I do not use assimp anymore
