### ISSUE TITLE
Setting up new project

### ISSUE THREAD

**Issue by VinnyVicious** [nem0/LumixEngine#1116]
- Do i build Lumix with my own project, or do i link dynamically?
- Is it possible to build a Lumix project with CMake?

**Comment by nem0** [comment]
See https://github.com/nem0/LumixEngine/wiki/Getting-started how to build Lumix on Linux
this travis script https://github.com/nem0/LumixEngine/blob/master/.travis.yml might be of some use

There is no CMake, Lumix uses genie as a project generator

**Comment by VinnyVicious** [comment]
I did read that. And i already built everything. But that's explaining how to build the engine, not a project using the engine. That's my question: Do i build Lumix with my own project, or do i link dynamically? Do i have to build the engine along with my projects?

**Comment by nem0** [comment]
@VinnyVicious aha, now I understand. 

Lumix is not really intended to be used as a library. It's more like Unity. 

I used this https://github.com/nem0/LumixEngine/wiki/Implementing-3rd-party-plugins  for my game -  where plugin == my game

It is possible to have your own ```int main()```, something like https://github.com/nem0/LumixEngine/blob/master/src/app/main_win.cpp, however there is not single click way to do that. I can add support for that if you are interested.

**Comment by VinnyVicious** [comment]
Oh, so the engine also publishes packages of my game? It does cross-platform compilation?

**Comment by nem0** [comment]
Lumix does not do any cross-compilation. It has to be done manually at the moment. Game package can be created in the studio.  Engine is not fully ported to Linux as you can see here https://github.com/nem0/LumixEngine/issues/655
