### ISSUE TITLE
Can not compile it successfully with clang, has any tip?

### ISSUE THREAD

**Issue by Qchrlis** [nem0/LumixEngine#1125]
**Configure:**
chrlis@chrlis-ThinkStation-P310:~/workspace/test/LumixEngine/projects$ ./genie_linux --gcc=linux-clang  gmake
Building configurations...
Running action 'gmake'...
Generating tmp/clang/Makefile...
Generating tmp/clang/engine.make...
Generating tmp/clang/physics.make...
Generating tmp/clang/renderer.make...
Generating tmp/clang/animation.make...
Generating tmp/clang/audio.make...
Generating tmp/clang/navigation.make...
Generating tmp/clang/lua_script.make...
Generating tmp/clang/unit_tests.make...
Generating tmp/clang/app.make...
Generating tmp/clang/editor.make...
Generating tmp/clang/studio.make...
Done.

**Building:**
chrlis@chrlis-ThinkStation-P310:~/workspace/test/LumixEngine/projects/tmp/clang$ make 
==== Building engine (debug64) ====
Creating obj/x64/Debug/engine/src/engine/fs/linux
Creating obj/x64/Debug/engine/src/engine/debug/linux
Creating obj/x64/Debug/engine/src/engine/linux
Creating obj/x64/Debug/engine/src/engine/mt/linux
path_utils.cpp
clang++: error: unable to execute command: Executable "clang++" doesn't exist!
engine.make:344: recipe for target 'obj/x64/Debug/engine/src/engine/path_utils.o' failed
make[1]: *** [obj/x64/Debug/engine/src/engine/path_utils.o] Error 1
Makefile:16: recipe for target 'engine' failed
make: *** [engine] Error 2

**audio.make:**
...
ifndef config
  config=debug64
endif

ifndef verbose
  SILENT = @
endif

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(MAKESHELL)))
  SHELLTYPE := posix
endif

ifeq (posix,$(SHELLTYPE))
  MKDIR = $(SILENT) mkdir -p "$(1)"
  COPY  = $(SILENT) cp -fR "$(1)" "$(2)"
  RM= $(SILENT) rm -f "$(1)"
else
  MKDIR = $(SILENT) mkdir "$(subst /,\\,$(1))" 2> nul || exit 0
  COPY  = $(SILENT) copy /Y "$(subst /,\\,$(1))" "$(subst /,\\,$(2))"
  RM    = $(SILENT) del /F "$(subst /,\\,$(1))" 2> nul || exit 0
endif

CC  = clang
CXX = clang++
AR  = ar

ifndef RESCOMP
  ifdef WINDRES
    RESCOMP = $(WINDRES)
  else
    RESCOMP = windres
  endif
endif

ifeq ($(config),debug64)
  OBJDIR     = obj/x64/Debug/audio
  TARGETDIR  = bin/Debug
...

**Comment by Qchrlis** [comment]
**Clang version:**
chrlis@chrlis-ThinkStation-P310:~/workspace/test/LumixEngine/projects/tmp/clang$ clang --version
clang version 3.6.2 (tags/RELEASE_362/final) 
Target: x86_64-unknown-linux-gnu
Thread model: posix

**Comment by nem0** [comment]
only GCC5 is supported/tested https://github.com/nem0/LumixEngine/wiki/Getting-started

**Comment by Qchrlis** [comment]
OK，thank you very much.
