### ISSUE TITLE
Undo/Redo commands broken after exiting GameMode

### ISSUE THREAD

**Issue by timbaker** [nem0/LumixEngine#1140]
1. Start the editor
2. Open universe > player
3. Select the 'player_camera' entity
4. Click 'Add script' under 'Lua Script' in Properties
5. Start Game Mode
6. Move or rotate the cube entity
7. Stop Game Mode
8. Click the 'Undo' button.  This should undo the AddScriptCommand but crashes.

stopGameMode() destroys the universe so must clear m_undo_stack I think. AddScriptCommand.scene points to the now-deleted LuaScriptScene.

**Comment by nem0** [comment]
Thanks for the report, I managed to reproduce it (strangely only in release mode) and will fix it ASAP
