### ISSUE TITLE
Improve shadow quality

### ISSUE THREAD

**Issue by nem0** [nem0/LumixEngine#1142]
* [x] improve leaking 
* [x] improve fake selfshadowing
* [x] improve shadows far from [0, 0, 0]
* [x] point light shadows
[Shadow pancaking](https://docs.unity3d.com/Manual/DirLightShadows.html)
http://cg.cs.uni-bonn.de/en/publications/paper-details/peters-2017-quantized-msm/

**Comment by nem0** [comment]
https://github.com/nem0/lumixengine_data/issues/99

**Comment by benwolf** [comment]
Shadow Cascades have what appears to be a gap between them especially between the first two cascades with leaves a visible line, appears to be a blending issue.

The further away cascades lighten very quickly, I am guessing from the lower resolution + burring. Reflection probes make this more obvious as they add more light information in the lighter areas compared to the dark.

**Comment by benwolf** [comment]
So been looking into the "gap issue" it's just an artifact between the low resolution shadowmap (1024) mixed with the blending amount and cascade distances. Adjusting the blend distance or the cascade distances or shadowmap resolution fixes it. So it's just a setting thing, not the actual shadow math.

Might be good add a variable to control the blend distance and expose it to the editor. Also maybe an option for Shadowmap resolution (although this is in main.lua already) but having it in editor would be easier to find ;)

**Comment by jamesdwebb** [comment]
Changed Lumix to use reverse Z on my fork, works well for improving the shadows far from the origin:

https://www.youtube.com/watch?v=YYfD0pAIplc
https://www.youtube.com/watch?v=tPQFAUvvQ4U

I'm partially using a hacked bgfx to do this at the moment though so it's not suitable for a PR and I'm not sure if you even want to use it by default.

**Comment by nem0** [comment]
@jamesdwebb looks great, what did you have to change in bgfx? Did you notice any negative effects with reversed z? I think it might be good as default.

**Comment by jamesdwebb** [comment]
In bgfx::setState I just swapped BGFX_STATE_DEPTH_TEST_LESS and BGFX_STATE_DEPTH_TEST_GREATER values rather than changing everything around in Lumix out of laziness.

No negative effects that I'm aware of. A few shaders (e.g. godrays, cubesky) need fixing to account for the change which I haven't got around to doing - I see no reason it would have a negative effect though.

**Comment by nem0** [comment]
@jamesdwebb reversed-z is now in master

**Comment by nem0** [comment]
reversed z in shaders: https://github.com/nem0/lumixengine_data/commit/ecb5cbf954fed29e6cc5f201bd5e448dcfa0b022

**Comment by jamesdwebb** [comment]
Many thanks @nem0! I'll try it out tonight.
