### ISSUE TITLE
Duplicate properties in Lua Script component

### ISSUE THREAD

**Issue by timbaker** [nem0/LumixEngine#1143]
In the 'player' universe I noticed the player.lua script properties  (camera_entity etc) appeared twice in the UI.
This seems to happen when a Lua script is already loaded in the Asset Browser when the universe is opened.

1. Start editor
2. Open Universe > player
3. Select player.lua in the Asset Browser
4. File > Open > player    (open the same 'player' universe again)
5. Now duplicate properties are displayed in the Properties panel for the player entity's player.lua script

If you put a breakpoint at resource.h:60 you'll see LuaScriptScene::onScriptLoaded() is getting called while deserializing the universe.

**Comment by nem0** [comment]
Thanks, fixed.

**Comment by timbaker** [comment]
Now the property grid displays the value in the Lua environment (m_state) instead of stored_value.

onScriptLoaded() is setting m_state in order for detectProperties() to work, but the game isn't running.  Perhaps m_state needs to be destroyed after detectProperties() is called?

**Comment by nem0** [comment]
@timbaker Is it causing any problems? ```stored_value``` and  ```m_state```'s value should be identical when the game is not running because of this https://github.com/nem0/LumixEngine/blob/master/src/lua_script/lua_script_system.cpp#L157

**Comment by timbaker** [comment]
Following the steps 1-4, I see the PLAYER_SPEED displays 1.0 when it should be 0.1.

```
deserializeLuaScript()
    setScriptPath()
        detectProperties() // applyProperty() is passed stored_value.c_str()=null here
    // now the properties values are read in
    int prop_count;
    serializer.read(&prop_count);
    for (int j = 0; j < prop_count; ++j)
    { ... }

```

**Comment by nem0** [comment]
Thanks, it's fixed too now. I guess I will refactor this code, it's quite messy.
