### ISSUE TITLE
Problem with importing makehuman model

### ISSUE THREAD

**Issue by Kenji245** [nem0/LumixEngine#1148]
i'm trying to import a model that i made with MakeHuman but i get weird error, the model is successfully imported but it keeping invisible and it seem to be had problem with the materials, i have uploaded the model maybe you can find out what exactly happened i also included the screenshot issue, here is the link goo.gl/W5EanH

**Comment by nem0** [comment]
See video in this zip [Desktop 07.05.2017 - 11.07.35.01.mp4.zip](https://github.com/nem0/LumixEngine/files/1124067/Desktop.07.05.2017.-.11.07.35.01.mp4.zip)
Use latest revision

**Comment by Kenji245** [comment]
now its working fine, thanks A lot @nem0 but it seem like the Bone is not imported because i cantik choose any Bone when i try to add Bone attachment component, i have tried to tick the "import all Bone" option in the asset importer but the model is become mess

**Comment by nem0** [comment]
Unfortunately, [assimp does not load skeletons and animations](http://assimp.sourceforge.net/lib_html/importer_notes.html) from blender files, you would have to convert it to fbx for that. I will drop assimp soon and the only supported format will be fbx anyway.

**Comment by Kenji245** [comment]
the engine keep crashing once i load the imported model, [here is the model](https://drive.google.com/open?id=0B1uORAzu1B8rSl9KZE9wWUV3a1E)

**Comment by Kenji245** [comment]
sorry for using the same folder name xD

**Comment by nem0** [comment]
try the latest executables

**Comment by nem0** [comment]
[makehuman.zip](https://github.com/nem0/LumixEngine/files/1132828/makehuman.zip)
