### ISSUE TITLE
RenderScene::castRay() scale issue

### ISSUE THREAD

**Issue by timbaker** [nem0/LumixEngine#1159]
I think RenderScene::castRay() needs this fix:

--			if (dotProduct(pos - origin, pos - origin) < radius * radius ||
++			if (dotProduct(pos - origin, pos - origin) < radius * scale * radius * scale ||

**Comment by nem0** [comment]
You are right. Do you have a bug caused by this, so I can verify my fix is correct?

**Comment by timbaker** [comment]
I only noticed this when using a model with scale = 0.002.  I noticed the framerate dropping when I looked in certain directions and tracked it down to castRay().
