### ISSUE TITLE
loadStyle()/saveStyle() simplification

### ISSUE THREAD

**Issue by ocornut** [nem0/LumixEngine#1161]
Was browsing your saving/loading code and found this:

https://github.com/nem0/LumixEngine/blob/5221fcfd751a49d35e12fa555f8034ed370a36af/src/editor/settings.cpp#L99

Both functions can use `ImGui::GetStyleColorName()` (previously `GetStyleColName()` just renamed it) to retrieve that string and iterate on loops from 0 to `ImGuiCol_COUNT` so you don't need to keep this block of enums in your code.

**Comment by nem0** [comment]
Changed, thanks.
