### ISSUE TITLE
BoneAttachment with detached bones

### ISSUE THREAD

**Issue by timbaker** [nem0/LumixEngine#1162]
If you run the attached project in GameView, you can see the cube entity lagging behind the animated model the cube is attached to.  The cube is attached to a bone that has no parent.  I was using this method to attach weapon models to the player hands.

[data.zip](https://github.com/nem0/LumixEngine/files/1253980/data.zip)

Also, I think this code needs to be moved from RenderSceneImpl::update() to lateUpdate().  The reason is, the animation plugin runs **after** the render plugin, so the bone attachments should be updated after the animation plugin has updated the pose.

`	void lateUpdate(float dt, bool paused) override
	{
		if (m_is_game_running)
		{
			m_is_updating_attachments = true;
			for (auto& bone_attachment : m_bone_attachments)
			{
				updateBoneAttachment(bone_attachment);
			}
			m_is_updating_attachments = false;
		}
	}
`

**Comment by nem0** [comment]
I did a quick fix. It solves this issue, however there are other issues with dependency order. Keeping this open until it's fixed.

**Comment by nem0** [comment]
Bone attachment dependencies should now be properly handled, including nested attachments.

**Comment by timbaker** [comment]
The cube entity still moves out of sync with the parent model.  It looks as though the parent's animation doesn't rotate as far as it should (or the bone the cube is attached to is moving further than it should).  I included the FBX file for comparison (in the models/TEST folder).  Perhaps it's a problem with the FBX importer?  Sorry I can't be more helpful fixing it.

**Comment by nem0** [comment]
When I use https://github.com/nem0/lumixengine_data/blob/master/scripts/debug/visualize_anim_bones.lua it looks synced with the bone itself. So I guess the problem is somewhere else. I will investigate further.

**Comment by nem0** [comment]
![image](https://user-images.githubusercontent.com/153526/29779767-da1b0018-8c13-11e7-9b04-33bd4879f439.png)
I found out that if Max position error and Max rotation error is something like 0.001, it works fine. 

I will investigate why there is such a huge error with default values and what can be done about it. I'm keeping this issue open for now, but setting the max error values should help in your case.

**Comment by nem0** [comment]
I've added adaptive error margin = smaller margin deeper in hierarchy. You example is not correct even with default values.
