### ISSUE TITLE
Coroutines & Fibers

### ISSUE THREAD

**Issue by nem0** [nem0/LumixEngine#1170]

**Comment by luckyycode** [comment]
how are you going to add linux support for that? I am pretty sure makecontext/swapcontext are deprecated

**Comment by nem0** [comment]
@luckyycode are they? I did not know. Are they in reality not working anywhere?

**Comment by luckyycode** [comment]
these functions are still available and working but marked as deprecated in posix (pthreads came to replace this)

**Comment by nem0** [comment]
https://github.com/JodiTheTigger/sewing/blob/master/src/sewing.c
