### ISSUE TITLE
Communism bindings

### ISSUE THREAD

**Issue by Alan-FGR** [nem0/LumixEngine#1187]
It's true, the commies are comming :trollface:

**Comment by nem0** [comment]
waiting for PR

**Comment by Alan-FGR** [comment]
in soviet russia the PR submits you :trollface:

**Comment by nem0** [comment]
don't close it, it has not been done yet

**Comment by Alan-FGR** [comment]
it'll be an honor to serve this cause my comrade!
*dies from starvation a day later*
*dies again from dysentery*
*is sent to gulag and works for a year*
*dies again from overworking*

**Comment by nem0** [comment]
can not reproduce, NMI
