### ISSUE TITLE
[Feature Request] Rain Entity and example of simple Camera Shake via Lua Code

### ISSUE THREAD

**Issue by Kenji245** [nem0/LumixEngine#1188]
well you have knew entity rain :trollface: so lets skip it 

For Camera Shake, i expect 2 kind of camera shake, first one is like the one in Gameplay of "The Evil Within" and the second one is like the one in T3D example (You will see this shake near Explosion) 

thanks at least to read this

**Comment by nem0** [comment]
Moving this to data
https://github.com/nem0/lumixengine_data/issues/67
https://github.com/nem0/lumixengine_data/issues/107
