### ISSUE TITLE
Lua Scripts crash on error

### ISSUE THREAD

**Issue by benwolf** [nem0/LumixEngine#1197]
Currently if a mistake is made in a Lua script (simple as a typo to a function call) the whole editor will crash. It really should fail gracefully and allow changes to be made and the script reloaded.

I know there is a issue for Lua debugging, but I hoped this could be dealt with just using the built in Lua error checking to prevent the script being run before it causes a whole editor crash.

**Comment by nem0** [comment]
![image](https://user-images.githubusercontent.com/153526/32883418-a3205b0c-cab7-11e7-859e-43aa19e45df7.png)

**Comment by nem0** [comment]
https://github.com/nem0/LumixEngine/commit/c510fd817f37031642715685b9665499f4c7da93
