### ISSUE TITLE
[Docking]Temporary glitch when changing tabs

### ISSUE THREAD

**Issue by vassvik** [nem0/LumixEngine#1199]
I've noticed that there sometimes are small temporary glitches when switching between certain tabs when using your docking extensions in my own programs. Consider the following gif: https://gfycat.com/BlaringThornyIberianemeraldlizard?speed=0.125, and you can see it when it changes from the "Log" to the "Properties" tab. It is not too visible with the color scheme of LumixEngine, but it stands more out with higher contrast color schemes.

**Comment by nem0** [comment]
Hi, thank you for reporting this. Author of imgui is already working on official docking solution, so I'm just waiting until it's finished and then I will use. Therefore I do not really want support my custom extension anymore.
