### ISSUE TITLE
[Docking] Strange extra lag when moving splitters

### ISSUE THREAD

**Issue by vassvik** [nem0/LumixEngine#1200]
When moving the splitters you can see that the activated splitter does not move as far as it should, resulting in it lagging behind more so than the regular expected input lag. This results in horizontal splitters (and other stretching gui elements in the neighbouring docks) overlapping a moving vertical splitter, and vice versa. 

Please look at the following capture: https://gfycat.com/ShockedOpenAchillestang?speed=0.125

**Comment by nem0** [comment]
see #1199
