### ISSUE TITLE
Occlusion culling

### ISSUE THREAD

**Issue by nem0** [nem0/LumixEngine#1204]
https://github.com/nem0/LumixEngine/wiki/Occlusion-culling
- [ ] optimizations, MT
- [ ] limit number of rasterized occluders
- [ ] do not rasterize occluders which are too small

**Comment by boberfly** [comment]
https://github.com/GameTechDev/MaskedOcclusionCulling possible lib candidate for the software version

**Comment by nem0** [comment]
58bf9aa7c4e73fb59dd2e848810d51f514047583
fd2c49a52f6890e04597d4dbe9b9fe9ca3d533c5
25a24916698625031157beaf34c178092ac6a457
