### ISSUE TITLE
How to do bloom or glow?

### ISSUE THREAD

**Issue by qntf** [nem0/LumixEngine#1207]
Hi, I'm a noob to this engine, how do I do bloom or glow? I have a cube that I want to glow, how can I do it?

**Comment by nem0** [comment]
Hi, you can see postprocesses in https://www.youtube.com/watch?v=Mul5-VCj57k 
Emissive materials are not yet implemented.

**Comment by qntf** [comment]
nice, i'm looking forward to it. Thanks for your work!

**Comment by nem0** [comment]
501f932ee3469031c3c586e316a15e612f952c46
