### ISSUE TITLE
Make an executable?

### ISSUE THREAD

**Issue by Tim4135** [nem0/LumixEngine#1248]
Hi.

I am creating my own engine too, and I am wondering if your engine can export an executable, and how you make it into an executable.
Could you tell me?

Thank you!

**Comment by nem0** [comment]
it can't create a selfcontained executable

**Comment by Tim4135** [comment]
But then, how are you going to release your game?

**Comment by nem0** [comment]
The game is pure data/scripts, run by common executable.

**Comment by Tim4135** [comment]
Is there any way I can access that?

**Comment by nem0** [comment]
I'm sorry, I don't understand, what do you want to access?

**Comment by Tim4135** [comment]
Well, what tool would I need to compile a lumix project to an executable?
Or doesn't that exist yet?

**Comment by Kenji245** [comment]
even godot use pre-compiled executable and copy it to every exported game directory

**Comment by nem0** [comment]
it's precompiled here https://github.com/nem0/lumixengine_data/blob/master/bin/app.exe
