### ISSUE TITLE
cannot make

### ISSUE THREAD

**Issue by lometsj** [nem0/LumixEngine#1249]
==== Building engine (debug64) ====
input_system.cpp
In file included from ../../../src/engine/lua_wrapper.h:6:0,
                 from ../../../src/engine/input_system.cpp:6:
../../../src/engine/metaprogramming.h:211:79: error: ‘const’ and ‘volatile’ function specifiers on ‘<anonymous>’ invalid in parameter declaration
 template <typename R, typename... Args> Tuple<Args...> argsToTuple(R(Args...) const);
                                                                               ^
../../../src/engine/metaprogramming.h:215:10: error: expected nested-name-specifier before ‘T’
 typename T declval();
          ^
../../../src/engine/metaprogramming.h:215:12: error: expected initializer before ‘declval’
 typename T declval();
            ^
../../../src/engine/metaprogramming.h:218:41: error: ‘declval’ was not declared in this scope
  using ArgsTuple = decltype(argsToTuple(declval<T>()));
                                         ^
../../../src/engine/metaprogramming.h:218:41: error: ‘declval’ was not declared in this scope
../../../src/engine/metaprogramming.h:218:50: error: expected primary-expression before ‘>’ token
  using ArgsTuple = decltype(argsToTuple(declval<T>()));
                                                  ^
../../../src/engine/metaprogramming.h:218:52: error: expected primary-expression before ‘)’ token
  using ArgsTuple = decltype(argsToTuple(declval<T>()));
                                                    ^
../../../src/engine/metaprogramming.h:219:40: error: ‘ArgsTuple’ was not declared in this scope
  using Type = typename TupleElement<N, ArgsTuple>::Head;
                                        ^
../../../src/engine/metaprogramming.h:219:49: error: template argument 2 is invalid
  using Type = typename TupleElement<N, ArgsTuple>::Head;
                                                 ^
engine.make:362: recipe for target 'obj/x64/Debug/engine/src/engine/input_system.o' failed
make[1]: *** [obj/x64/Debug/engine/src/engine/input_system.o] Error 1
Makefile:16: recipe for target 'engine' failed
make: *** [engine] Error 2

**Comment by nem0** [comment]
fixed
