### ISSUE TITLE
Changing material on a skinned mesh prevents skinning/animation from working

### ISSUE THREAD

**Issue by atw-will** [nem0/LumixEngine#1251]
Pretty much what it says on the tin. Creating a new material and adding it to an existing mesh works fine, but if that mesh is animated then it no longer animates and remains in t-pose.
However, when you start game mode in the editor, the outline actually does perform the animation!
![anim_problem](https://user-images.githubusercontent.com/25671370/42430916-225066ac-833a-11e8-8c7a-b36770e9d0bc.png)

**Comment by atw-will** [comment]
I've been doing my own digging on this one, in case it was something straightforward. I tried adding a clause to setMaterial to set the SKINNED define in the Material object for skinned models, but that doesn't seem to have done it.

**Comment by Kenji245** [comment]
i ever get the same issue, save all entity change you have made and bring it to the new scene/level, lets see if it fix it for you.

**Comment by atw-will** [comment]
So the red material above is a very simple material as so:

{"render_layer" : "default",
"layers_count" : 0,
"shader" : "pipelines/rigid/rigid.shd",
"backface_culling" : true,
"texture" : {"source" : ""},
"texture" : {"source" : ""},
"texture" : {"source" : ""},
"texture" : {"source" : ""},
"defines" : [],
"uniforms" : [{"name" : "u_time",
"time" : 0},
{"name" : "u_parallaxScale",
"float_value" : 0.00000000}],
"metallic" : 0.43000002,
"roughness" : 0.28000000,
"emission" : 0.00000000,
"alpha_ref" : 0.30000000,
"color" : [1.00000000,
0.19607843,
0.19607843,
1.00000000]}

That's the version imported from the mesh. If you create a copy of that material file and rename it, then assign it as the material for any animated mesh, the animations stop working. I just replaced the squirrel's materials in the tutorial project and confirmed it does break it.

**Comment by nem0** [comment]
should be fixed
