### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [nem0/LumixEngine#1254]
Would you like to add more error handling for return values from functions like the following?
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [OSXMutex constructor](https://github.com/nem0/LumixEngine/blob/0aa105e74046e6cb04587deef87290a27b45587d/src/engine/mt/osx/mutex.cpp#L58)
- [sendfile](http://man7.org/linux/man-pages/man2/sendfile.2.html "Transfer data between file descriptors.") ⇒ [copyFile](https://github.com/nem0/LumixEngine/blob/3518f5dc5be5ec2e3a9b05dcc31691c88f502393/src/engine/linux/system.cpp#L14)

**Comment by nem0** [comment]
Linux version does not exist anymore
