### ISSUE TITLE
FFR dx backend

### ISSUE THREAD

**Issue by nem0** [nem0/LumixEngine#1259]

**Comment by raizam** [comment]
no kidding :)

**Comment by Alan-FGR** [comment]
dx or just d3d? if so, d3d11?

**Comment by nem0** [comment]
ffr is just for rendering, d3d11

**Comment by Alan-FGR** [comment]
i thought you were talking about loomigz :facepalm:

**Comment by luckyycode** [comment]
Why did you move away from bgfx? I am just curious
and what about Vulkan support ☺️?

**Comment by nem0** [comment]
It's more fun to code stuff from scratch. Also, superb perf.

**Comment by luckyycode** [comment]
Can't disagree, okay.

**Comment by luckyycode** [comment]
By the way, what ffr does mean?

**Comment by nem0** [comment]
for fun renderer :)

**Comment by nem0** [comment]
https://github.com/nem0/lumixengine_dx11/
