### ISSUE TITLE
mobile support? android，yet iOS?

### ISSUE THREAD

**Issue by acgleader** [nem0/LumixEngine#1264]

**Comment by mafiesto4** [comment]
GI when?

**Comment by nem0** [comment]
@acgleader lumix is PC-centric, I don't have manpower to properly support mobile.
@mafiesto4 after Flax is MIT :trollface:

**Comment by Alan-FGR** [comment]
> I don't have manpower to properly support mobile.

You don't have **power** @nem0... either battery or processing. Stop pretending you're a real boi :trollface:
