### ISSUE TITLE
LuaJit allocation troubles - random crashes

### ISSUE THREAD

**Issue by Alan-FGR** [nem0/LumixEngine#1287]
I'm having random crashes on my machine. I managed to track the problem down to [this ntavm call](https://github.com/LuaJIT/LuaJIT/blob/f0e865dd4861520258299d0f2a56491bd9d602e1/src/lj_alloc.c#L147) which was returning some boolsheet value that isn't even a valid ntstatus.

Toggling [this](https://github.com/LuaJIT/LuaJIT/blob/f0e865dd4861520258299d0f2a56491bd9d602e1/src/lj_alloc.c#L85) as suggested on Gitter didn't fix the problem just changed the behavior and made it even harder to reproduce.

Hardware fault isn't discarded in this case, although I think that's unlikely since everything else works perfectly fine.

**Comment by nem0** [comment]
Sucks :trollface:

**Comment by raizam** [comment]
just use godot

**Comment by nem0** [comment]
or archetypes

**Comment by Alan-FGR** [comment]
Configuring luajit to use gc64 seems to have solved this problem.
Related: https://github.com/LuaJIT/LuaJIT/issues/419

**Comment by nem0** [comment]
fixed a737f44424232232304afea4fffa3a2c267d8e77
https://github.com/nem0/LuaJIT/commit/413624fffee3a6d29d3161180f6278fa7cd3207b
