### ISSUE TITLE
Terrain detail textures

### ISSUE THREAD

**Issue by nem0** [nem0/LumixEngine#1292]

**Comment by VinnyVicious** [comment]
Can we use this already? How can we define detail textures?

**Comment by nem0** [comment]
The newly created terrain is acutally usable now by default in the latest commit

![image](https://user-images.githubusercontent.com/153526/77011617-88291680-696c-11ea-8c74-46a2074807e7.png)
![image](https://user-images.githubusercontent.com/153526/77011656-a42cb800-696c-11ea-8ac2-7e85ea8d6218.png)
