### ISSUE TITLE
crash when picking terrain

### ISSUE THREAD

**Issue by BenjaminGu** [nem0/LumixEngine#1300]
Steps to reproduce:

1. create a terrain
2. set terrain heightmap to the attached texture file(cottage_terrain.png).
3. click on terrain to pick
4. crash!!

repro rate: 100%

![terrain_picking_crash](https://user-images.githubusercontent.com/16999381/67153910-f4a3d900-f32c-11e9-9da6-3261c876ec56.png)
![cottage_terrain](https://user-images.githubusercontent.com/16999381/67153905-e786ea00-f32c-11e9-9b41-371cde571591.png)

**Comment by nem0** [comment]
Hi, there's now an error message (and no cras) saying that png can not be used for heightmaps. You can however convert png to raw in asset browser.
![image](https://user-images.githubusercontent.com/153526/67157416-0df85580-f32c-11e9-9b2a-1090ab0c2b14.png)
