### ISSUE TITLE
Fbx animations

### ISSUE THREAD

**Issue by divinon** [nem0/LumixEngine#1305]
Hello nem0, fbx files can have bones with only rotation or translation animation curves, the asset compiler doesn't complain but there are asserts like:
https://github.com/nem0/LumixEngine/blob/f40745ffc43d93251988906baa8097d0c6c3ec72/src/animation/animation.cpp#L160
I solved by adding: 
`pos[model_bone_index] = model.getBone(model_bone_index).relative_transform.pos;`

Unrelated note, I was having random crashes while closing the editor, it was in a String::~String(), its m_allocator was already deleted (full of pure calls). The string was in 'g_log_error' which is a thread_local, so it seems that the static 'DefaultAllocator g_allocator' was deleted before than a thread_local. This was on MSVC of VS2017.
Recompiled and never happened again. When it was happening m_cstr in String was always null, this could be a possible dirty workaround to avoid m_allocator.deallocate.

**Comment by nem0** [comment]
Should be fixed, I don't have an fbx with with rotations or translations only, so it's bit of a blind fix.

**Comment by divinon** [comment]
Sorry but it is a bit worse, now even fbxs from Blender fail at:
https://github.com/nem0/LumixEngine/blob/master/src/animation/animation.cpp#L312
Anyway no need to worry about this, for me it was enough to apply the bone location if there was no location curve. What data is written in a fbx seems different from an application to another, supporting everything can be a real pain. If you think it's worth it, then [SketchFab ](https://sketchfab.com/3d-models?features=downloadable+animated) has some fbxs to test.
Unrelated: with a scene view in focus private memory is skyrocketing, it is something in the main pipeline or another lua quirk.

**Comment by nem0** [comment]
I tried some animations from sketchfab like https://sketchfab.com/3d-models/buster-drone-294e79652f494130ad2ab00a13fdbafd and they work fine, do you have some specific animation which does not work? Meanwhile I made another blind fix for this issue.

I'm investigating the memory leak. Most of Lumix stuff uses Lumix leak detector, so I suspect it's some 3rd party allocating. Since even VS heap debugger does not show any leaks, I suspect gpu driver. I have to investigate more.

**Comment by nem0** [comment]
the leak is fixed

**Comment by divinon** [comment]
All the problems are now fixed, thank you.
On sketchfab I've found some models that have some other kind of issues, if you want to look into them I've sent you a file by email.

I think the LOWORD and HIWORD for the x, y window position must be casted to "i16", otherwise a negative value will be interpreted as uint16 and the window will vanish:
https://github.com/nem0/LumixEngine/blob/20a102fb77bccebe500d3a00d892827bf0d93416/src/engine/win/os.cpp#L426

**Comment by nem0** [comment]
Thanks, nice catch, fixed.

**Comment by nem0** [comment]
I've found some problematic fbx on sketchfab too, looking into it. Got your email too, will look into it.

**Comment by nem0** [comment]
dbc608691635b48c5ec39b5bd18c948c84861e89
