### ISSUE TITLE
Additive loading of worlds

### ISSUE THREAD

**Issue by nem0** [nem0/LumixEngine#1309]
load additively whole worlds, it allows to keep UI world while switching game worlds

**Comment by raizam** [comment]
I notice you self-assigned this, and it shows this large scale project is well organized

**Comment by nem0** [comment]
@raizam should I assign this to you?

**Comment by raizam** [comment]
![](https://files.gitter.im/nem0/LumixEngine/DNcU/image.png)

if it's already done I can handle it yeah :trollface:

**Comment by nem0** [comment]
@raizam assigned

**Comment by raizam** [comment]
@nem0 I mistakenly unassigned it

**Comment by nem0** [comment]
@raizam no problem, reassigned

**Comment by raizam** [comment]
@rokups yo need help. got trapped by robot in honeypot

**Comment by rokups** [comment]
You are doomed.

**Comment by nem0** [comment]
#1233 duplicate
