### ISSUE TITLE
any tutorial?

### ISSUE THREAD

**Issue by englishfarsi** [nem0/LumixEngine#1314]
Hi. Is there any tutorial or more info about this game engine? scripting languages? (is it supports c++ scripting or only supports Lua? what about features? ("A lot of stuff" is not enough).  please share more info and especially about scripting language, licence (is it Free and open source or only open source) and share a beginner tutorial.
thank you.

**Comment by nem0** [comment]
Hi, thanks for the suggestion but I don't have the manpower to create docs and tutorials. If you want open source engine I recommend https://godotengine.org/ it has biggest community from open source engines by far, plenty of tutorials and videos.
