### ISSUE TITLE
License

### ISSUE THREAD

**Issue by calebROlson** [nem0/LumixEngine#1321]
Your Lent library is licensed as GPL. 

Doesn't that effectively make this whole engine and likewise any software made commercially available using this engine also GPL? Your current license is described as MIT.

Thanks for all the interesting code to read. I live vicariously through you.

Also by extension, you would own my kidney.

**Comment by calebROlson** [comment]
I am now undergoing dialysis three times a week. Thanks a lot.

**Comment by nem0** [comment]
Hmm, you are totally right. And since half of the world is based on Lent, they all break the license. I need to contact my lawyer.

**Comment by calebROlson** [comment]
> half of the world is based on Lent
**$$$$$$$**


My grandmother has been using it for decades and is using her stimulus check to pay you royalties. She can't even pay for her dialysis. Other than this urgent bug, thank you for your service.
