### ISSUE TITLE
A few questions regarding this project

### ISSUE THREAD

**Issue by Joe23232** [nem0/LumixEngine#1331]
Hi I have a few questions regarding this game engine:

1. Am I able to configure the game using C++?
2. Is this game engine kinda like [Toy](https://hugoam.github.io/toy-io/) game engine where the entire library and everything gets compiled into the game?
3. Is it released as stable?
4. Is this game engine as easy to learn as Unity3D?
5. Does it support gltf 3D object formats?

**Comment by nem0** [comment]
No, yes, no, no, yes.
