### ISSUE TITLE
All Shapes Are black

### ISSUE THREAD

**Issue by calegxm999** [nem0/LumixEngine#1332]
Isn't the title self explanatory?

**Comment by calegxm999** [comment]
Screenshot:
![Lumix Studio - RetroVerse 24_08_2020 8_28_07 AM](https://user-images.githubusercontent.com/51974788/90990346-27210100-e5e4-11ea-8850-6c79413278b7.png)
GPU:
Intel(R) HD Graphics 615
Driver Version:
24.20.100.6286
CPU:
Intel(R) Core(TM) m3-7Y30 CPU @ 1.00GHz (4 CPUs), ~1.6GHz
OS:
Windows 10 Enterprise 64-bit (10.0, Build 17763) (17763.rs5_release.180914-1434)
Revision: (Does that mean version?)
https://github.com/nem0/LumixEngine/releases/tag/ffr_prototype

**Comment by nem0** [comment]
https://github.com/nem0/LumixEngine/releases/tag/ffr_prototype is just an old feature tag, you have to use the latest master

**Comment by calegxm999** [comment]
thanks....
