### ISSUE TITLE
Black screen on run in windows 10 DirectX 11.1

### ISSUE THREAD

**Issue by Harshharsh2275** [nem0/LumixEngine#1336]
I have DirectX 11 support but while running the engine it stops at a black screen please tell me a fix

**Comment by nem0** [comment]
Hi, does it render anything before going black? Could you post lumix.log here?

**Comment by Harshharsh2275** [comment]
i don't know if it render anything but the screen is like grey not black actually here's the image:
![error_lumix](https://user-images.githubusercontent.com/53533396/96972378-12091580-1534-11eb-8b19-633ca7e553d0.png)

And here's the lumix.log file:
[lumix.log](https://github.com/nem0/LumixEngine/files/5428125/lumix.log)

**Comment by nem0** [comment]
Grey is default UI background, so it seems it's rendering something. There's no error in lumix.log either. I've no idea what could be the issue. Does OpenGL version work?

**Comment by Harshharsh2275** [comment]
> Grey is default UI background, so it seems it's rendering something. There's no error in lumix.log either. I've no idea what could be the issue. Does OpenGL version work?

No it doesn't work my opengl is 3.0

**Comment by nem0** [comment]
There have been many fixes, is this still an issue?

**Comment by Harshharsh2275** [comment]
> There have been many fixes, is this still an issue?

Let me try again
