### ISSUE TITLE
Error message when using fbx without mesh

### ISSUE THREAD

**Issue by nem0** [nem0/LumixEngine#1338]
Asset browser in editor prints error messages when there are FBXs without meshes (e.g. animation only files from mixamo)

**Comment by rijx** [comment]
I tried to reproduce this and I got

```
Could not open models/old man idle.fbx
Failed to load models/old man idle.fbx
```

Is that the error message?

**Comment by nem0** [comment]
* if it's file with a mesh, it's a bug.
* if it's a file with animations only, you can safely ignores it. `something.ani:file.fbx` is created and can be used. The error is caused by the fact, that asset browser is trying to preview the file, but there's no mesh.

**Comment by rijx** [comment]
So what’s the bug(fix)? Should the .fbx containing the animations be hidden because it’s empty / useless?

**Comment by nem0** [comment]
It's not useless, because you can click on it and set import parameters. I will have to think about how to properly fix this.
