### ISSUE TITLE
allocator.cpp': No such file or directory

### ISSUE THREAD

**Issue by marshal-it** [nem0/LumixEngine#1340]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open source file: '..\..\..\src\engine\allocator.cpp': No such file or directory	engine	D:\GitHub\LumixEngine\projects\tmp\vs2019\c1xx	1

**Comment by nem0** [comment]
I'm sorry, I don't understand. How do I reproduce this?

**Comment by marshal-it** [comment]
update master today. I found no allocator.cpp in the project and vs2019 build error like this, may be I update wrong?

**Comment by nem0** [comment]
oh, try to regenerate project either with `main.bat` in `projects` dir or running `genie.exe vs2019` in `projects` dir

**Comment by marshal-it** [comment]
I use the main.bat error again,  but I use vs2019 Professional. 
  c1xx : fatal error C1083: Cannot open source file: '..\..\..\src\engine\allocator.cpp': No such file or directory [D:
\GitHub\LumixEngine\projects\tmp\vs2019\engine.vcxproj

**Comment by nem0** [comment]
1. delete `projects/tmp` to be sure vs solution will be updated
2. run `main.bat`
3. select `2. Create project`
4. open solution in vs and build

**Comment by marshal-it** [comment]
Thanks
