### ISSUE TITLE
play demo Assert error.

### ISSUE THREAD

**Issue by marshal-it** [nem0/LumixEngine#1341]
![image](https://user-images.githubusercontent.com/3109971/100700087-9b372600-33d7-11eb-961b-54fd32d6cfb2.png)

**Comment by nem0** [comment]
Hi, how can I reproduce this? Demo runs ok for me. Does this always happen?

**Comment by nem0** [comment]
I managed to reproduce it after all, I had to delete baked files. Fixed, thanks for the report.
