### ISSUE TITLE
Add comments in the main.bat script

### ISSUE THREAD

**Issue by Jurgon96** [nem0/LumixEngine#1358]
Add comments in the main.bat script
Intention to publicize the project within the file itself to clarify the implementation of each of the aspects.
Start with the main file first.

**Comment by nem0** [comment]
Could you clarify which parts in main.bat are not clear?

**Comment by rijx** [comment]
Hey Jurgon,

In general no code comments are used in Lumix. Easy to read code and generous use of variable and function names are preferred instead.

I'm going to close this issue now. Feel free to ask questions about specific code and if needed we'll refactor or add comments if it's confusing.
