### ISSUE TITLE
Comment /studio/main files from both linux and Windows

### ISSUE THREAD

**Issue by Jurgon96** [nem0/LumixEngine#1362]

**Comment by nem0** [comment]
Do you mean this file https://github.com/nem0/LumixEngine/blob/master/src/studio/win/main.cpp? What comments do you expect? The engine does not have any code comments and I don't plan to use comments.

**Comment by rijx** [comment]
Hey Jurgon,

This issue has been open for 11 days without clarification.

I'm going to close this issue. Feel free to create a new one with details on what you're trying to accomplish and we'll try to help you.
