### ISSUE TITLE
Disable API Camera

### ISSUE THREAD

**Issue by Jurgon96** [nem0/LumixEngine#1363]
The client demands that the editor's main camera be modified. For the moment disable original.

**Comment by nem0** [comment]
I'm sorry, that sentence does not make much sense to me.

**Comment by Planebagels** [comment]
I think he google translated that.

**Comment by nem0** [comment]
Yes, it's exactly the same as his original spanish text put in google translate. Unfortunately it does not make much sense to me

**Comment by Planebagels** [comment]
I found his other issues and I translated those with google translate, DeepL etc. Translating it into DeepL gave me the most understandable answer "The customer requires to modify the main camera of the editor. Disable original for the moment."

**Comment by rijx** [comment]
Hey Jurgon,

This issue has been open for 11 days without clarification.

I'm going to close this issue. Feel free to create a new one with details on what you're trying to accomplish and we'll try to help you.
