### ISSUE TITLE
Using global variables in the studio_app.cpp file

### ISSUE THREAD

**Issue by Jurgon96** [nem0/LumixEngine#1364]

**Comment by nem0** [comment]
There are no global variables in studio_app.cpp.

**Comment by rijx** [comment]
Hey Jurgon,

Thank you for your issue. Like Mikulas said there are no global variables in that file. I think there may be a misunderstanding here.

I'm going to close this issue as it has been 11 days with no response. Feel free to open a new one if you can include a permalink to the code in question.
