### ISSUE TITLE
Building Issue 

### ISSUE THREAD

**Issue by PowerX-NF** [nem0/LumixEngine#1384]
I Just Downloaded Lumix Source and tried to compile it to visual studio and got this error

 'Lumix::GUIScene::TextHAlign (__cdecl Lumix::GUISceneImpl::* )(Lumix::EntityRef)': too many arguments for call
				return static_cast<i32>((static_cast<C*>(scene)->*Getter)(e, idx));
@nem0

**Comment by nem0** [comment]
Is this VS2019? It builds fine on build machine https://github.com/nem0/LumixEngine/actions/runs/888264477
