### ISSUE TITLE
crashed on deepin 20

### ISSUE THREAD

**Issue by windyslove** [nem0/LumixEngine#1386]
build successfully
crashed when i try to  run studio

**Comment by nem0** [comment]
Hi, which os? if win, do you run it from VS? crash callstack?

**Comment by windyslove** [comment]
@nem0  Linux os . built and run from shell.
I put crash log next day.

**Comment by windyslove** [comment]
@nem0 build from lumix_bootstrap.sh
crash output
windyslove@windyslove-PC:/media/windyslove/DATA/Development$ ./lumix_bootstrap.sh 
fatal: 目标路径 'LumixEngine' 已经存在，并且不是一个空目录。
fatal: 目标路径 'lumixengine_linux_3rdparty_bin' 已经存在，并且不是一个空目录。
cp: 无法获取'lumixengine_linux_3rdparty_bin/cmft/libcmft.a' 的文件状态(stat): 没有那个文件或目录
cp: 无法获取'lumixengine_linux_3rdparty_bin/nvtt/*.a' 的文件状态(stat): 没有那个文件或目录
sh: 1: Syntax error: end of file unexpected (expecting "then")
Building configurations...
Running action 'gmake'...
Done. Generated 0/11 projects.
==== Building engine (debug64) ====
plugin.cpp
obj/x64/Debug/engine/external/imgui/imgui_unity.o obj/x64/Debug/engine/src/engine/allocators.o obj/x64/Debug/engine/src/engine/core.o obj/x64/Debug/engine/src/engine/crc32.o obj/x64/Debug/engine/src/engine/engine.o obj/x64/Debug/engine/src/engine/file_system.o obj/x64/Debug/engine/src/engine/geometry.o obj/x64/Debug/engine/src/engine/input_system.o obj/x64/Debug/engine/src/engine/job_system.o obj/x64/Debug/engine/src/engine/linux/atomic.o obj/x64/Debug/engine/src/engine/linux/controller_device.o obj/x64/Debug/engine/src/engine/linux/debug.o obj/x64/Debug/engine/src/engine/linux/fibers.o obj/x64/Debug/engine/src/engine/linux/os.o obj/x64/Debug/engine/src/engine/linux/sync.o obj/x64/Debug/engine/src/engine/linux/thread.o obj/x64/Debug/engine/src/engine/log.o obj/x64/Debug/engine/src/engine/lua_api.o obj/x64/Debug/engine/src/engine/lua_wrapper.o obj/x64/Debug/engine/src/engine/lz4.o obj/x64/Debug/engine/src/engine/math.o obj/x64/Debug/engine/src/engine/page_allocator.o obj/x64/Debug/engine/src/engine/path.o obj/x64/Debug/engine/src/engine/plugin.o obj/x64/Debug/engine/src/engine/prefab.o obj/x64/Debug/engine/src/engine/profiler.o obj/x64/Debug/engine/src/engine/reflection.o obj/x64/Debug/engine/src/engine/resource.o obj/x64/Debug/engine/src/engine/resource_manager.o obj/x64/Debug/engine/src/engine/stream.o obj/x64/Debug/engine/src/engine/string.o obj/x64/Debug/engine/src/engine/universe.o
Archiving engine
==== Building editor (debug64) ====
studio_app.cpp
bin/Debug/libengine.a
obj/x64/Debug/editor/src/editor/asset_browser.o obj/x64/Debug/editor/src/editor/asset_compiler.o obj/x64/Debug/editor/src/editor/entity_folders.o obj/x64/Debug/editor/src/editor/gizmo.o obj/x64/Debug/editor/src/editor/linux/file_system_watcher.o obj/x64/Debug/editor/src/editor/log_ui.o obj/x64/Debug/editor/src/editor/prefab_system.o obj/x64/Debug/editor/src/editor/profiler_ui.o obj/x64/Debug/editor/src/editor/property_grid.o obj/x64/Debug/editor/src/editor/settings.o obj/x64/Debug/editor/src/editor/spline_editor.o obj/x64/Debug/editor/src/editor/studio_app.o obj/x64/Debug/editor/src/editor/utils.o obj/x64/Debug/editor/src/editor/world_editor.o
Archiving editor
==== Building renderer (debug64) ====
==== Building audio (debug64) ====
bin/Debug/libengine.a bin/Debug/libeditor.a
Archiving audio
bin/Debug/libengine.a bin/Debug/libeditor.a
Archiving renderer
==== Building lua_script (debug64) ====
==== Building gui (debug64) ====
==== Building animation (debug64) ====
==== Building physics (debug64) ====
==== Building navigation (debug64) ====
bin/Debug/libengine.a bin/Debug/librenderer.a bin/Debug/libeditor.a
bin/Debug/libengine.a bin/Debug/librenderer.a bin/Debug/libeditor.a
Archiving lua_script
Archiving gui
bin/Debug/libengine.a bin/Debug/librenderer.a bin/Debug/libeditor.a
Archiving animation
bin/Debug/libengine.a bin/Debug/librenderer.a bin/Debug/libeditor.a
Archiving navigation
bin/Debug/libengine.a bin/Debug/libeditor.a bin/Debug/librenderer.a
Archiving physics
==== Building studio (debug64) ====
bin/Debug/libphysics.a bin/Debug/librenderer.a bin/Debug/libaudio.a bin/Debug/liblua_script.a bin/Debug/libgui.a bin/Debug/libanimation.a bin/Debug/libnavigation.a bin/Debug/libeditor.a bin/Debug/libengine.a
Linking studio
sysname: Linux
nodename: windyslove-PC
release: 5.12.18-amd64-desktop
version: #1 SMP Tue Jul 20 15:26:54 CST 2021
machine: x86_64
Engine created.
OpenGL version: 4.6 (Compatibility Profile) Mesa 20.3.4
OpenGL vendor: Intel
OpenGL renderer: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
PCM name: 'default'
PCM state: '3'
Error: Could not create /media/windyslove/DATA/Development/LumixEngine/data/.lumix/assets
Initializing editor...
Error: Could not create /media/windyslove/DATA/Development/LumixEngine/data/.lumix/asset_tiles
Loading settings...
Initializing imgui...
Loading settings...
Startup took 2.657445 s
Segmentation fault

**Comment by nem0** [comment]
> Error: Could not create /media/windyslove/DATA/Development/LumixEngine/data/.lumix/assets

maybe it's some permissions issue?

**Comment by windyslove** [comment]
in directory LumixEngine run studio with sudo 
crash any way

sudo ../projects/tmp/gmake/bin/Debug/studio
sysname: Linux
nodename: windyslove-PC
release: 5.13.13-amd64-desktop
version: #1 SMP Tue Aug 31 18:01:11 CST 2021
machine: x86_64
Engine created.
OpenGL version: 4.6 (Compatibility Profile) Mesa 20.3.4
OpenGL vendor: Intel
OpenGL renderer: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
PCM name: 'default'
PCM state: '3'
Initializing editor...
Error: Could not create /media/windyslove/DATA/Development/LumixEngine/data/.lumix/asset_tiles
Loading settings...
Initializing imgui...
Loading settings...
Startup took 0.601024 s
段错误

**Comment by windyslove** [comment]
I found directory .lumix/asset_tiles and .lumix/asset already created under /data

**Comment by nem0** [comment]
Log looks ok, I would need callstack to move forward with this.

**Comment by windyslove** [comment]
ltrace log

[log.log](https://github.com/nem0/LumixEngine/files/7111142/log.log)

**Comment by windyslove** [comment]
ltrace log

[log.log](https://github.com/nem0/LumixEngine/files/7111145/log.log)

**Comment by nem0** [comment]
is this still happening in latest version?

**Comment by windyslove** [comment]
I'm not going on with this project.I close this issue,thanks for your help.
