### ISSUE TITLE
ImGui:Font Atlas not built. Did you call io.Fonts->GetTexDataAsRGBA32() / GetTexDataAsAlpha8()?

### ISSUE THREAD

**Issue by Ehobits** [nem0/LumixEngine#1387]
This happens when compiling the DX11 version in VS2017. I don't quite understand that the **EditorUIRenderPlugin (StudioApp& app)** does not seem to be executed.

**This is the message that pops up when running alone:
ImGui::CheckNewFremeSanityChecks
ImGui::NewFrame
Lumix::StudioAppImpl::guiBEginFrame
Lumix::StudioAppImpl::update
Lumix::StudioAppImpl::onldle
<lambda_6b4fc3f5333703250ea5a5d1cb2243fd>::operator()
<lambda_6b4fc3f5333703250ea5a5d1cb2243fd>::<lambda_invoker_cdecl>
Lumix::jobs::manage
RegQueryInfoKeyA
RtlUserFiberStart
RtlUserFiberStart

code:2147483651
Address:140698327285854
Base:140698323124224**

and here's the lumix.log file:
[lumix.log](https://github.com/nem0/LumixEngine/files/7193709/lumix.log)

**Comment by nem0** [comment]
Hi, can you post your src/engine/plugins.inl?
