### ISSUE TITLE
detectProperties

### ISSUE THREAD

**Issue by divinon** [nem0/LumixEngine#1398]
https://github.com/nem0/LumixEngine/blob/81d0ba60fe604b100fe8bcb44ee09a59f866812a/src/lua_script/lua_script_system.cpp#L453
Hello, by its use with sizeof and memset, it should be an u8 array.

**Comment by nem0** [comment]
You are right!

**Comment by nem0** [comment]
Fixed in 41d9945b6d419fec5dea9e6e81ddef55de0bd1a9
