### ISSUE TITLE
Is native scripting still possible?

### ISSUE THREAD

**Issue by Tom2456** [nem0/LumixEngine#1428]
I read the wiki and it said the plugin is for an older version. Is there any other way to code in c++? Or is it still possible and Im just stupid? I would like to know.

**Comment by nem0** [comment]
Hi, I use https://github.com/nem0/LumixEngine/wiki/Custom-plugin for my games

**Comment by Tom2456** [comment]
Oh thanks. But wait, do you just make a custom plugin to make native scripting possible or do you do the logic in the plugin? (Sorry if this is a stupid question I have never made a plugin before)

**Comment by nem0** [comment]
I do logic in a plugin. There's even hotreload for plugins https://github.com/nem0/LumixEngine/wiki/Plugin-hotreload but I don't use it, so there might be bugs in newer versions

**Comment by Tom2456** [comment]
Ok, I'll try that. thanks!
