### ISSUE TITLE
OS X port

### ISSUE THREAD

**Issue by nem0** [nem0/LumixEngine#15]
- [ ] compile 3rd party libraries
- [ ] [audio](https://github.com/nem0/LumixEngine/tree/master/src/audio)
- [ ] [editor](https://github.com/nem0/LumixEngine/tree/master/src/editor/pc)
- [ ] [debug](https://github.com/nem0/LumixEngine/tree/master/src/engine/debug/pc)
- [ ] [core](https://github.com/nem0/LumixEngine/tree/master/src/engine/core/pc)
- [ ] [MT](https://github.com/nem0/LumixEngine/tree/master/src/engine/core/MT/pc)
- [ ] [FS](https://github.com/nem0/LumixEngine/tree/master/src/engine/core/FS/pc)
- [ ] [app](https://github.com/nem0/LumixEngine/blob/master/src/app/main.cpp)
- [ ] [studio](https://github.com/nem0/LumixEngine/blob/master/src/studio/main.cpp)
- [ ] OpenGL version of BGFX, maybe shaders
- [ ] Release mode

---
- [ ] Continuous Integration
- [ ] Docs

**Comment by nem0** [comment]
XOXO, closed 
:trollface:

**Comment by gideongrinberg** [comment]
Any update?

**Comment by nem0** [comment]
Not on my TODO list.
