### ISSUE TITLE
Skeletal mesh not rendering properly on AMD gpu's 

### ISSUE THREAD

**Issue by CitroenGames** [nem0/LumixEngine#1501]
![image](https://github.com/nem0/LumixEngine/assets/54474809/0f1eec56-080b-42ed-907a-9cfc5c942545)
this is from the demo scene
![image](https://github.com/nem0/LumixEngine/assets/54474809/92f809f7-c2f1-40c6-a4e9-c2ba6e53b34b)
and this is from the fps demo scene.

as seen in the screenshots they dont seem to render properly.

GPU: AMD RX 6950 XT 
Driver: 24.5.1
OS: WIndows 10 22H2

**Comment by CitroenGames** [comment]
![image](https://github.com/nem0/LumixEngine/assets/54474809/107b73cb-a1a8-4e1a-9be3-ce3ed091995f)
normal mesh rendering seems to work fine

**Comment by nem0** [comment]
Hi, have you tried using DX instead of OpenGL?

**Comment by CitroenGames** [comment]
Oh Hi! 

Could you explain how i can switch from rendering api?

**Comment by CitroenGames** [comment]
i think you were referring to this
https://github.com/nem0/lumixengine_dx

**Comment by nem0** [comment]
Yes, that's it. Just run `projects/main.bat` -> plugins -> dx. It will download DX plugin and regenerate VS project.

**Comment by CitroenGames** [comment]
![image](https://github.com/nem0/LumixEngine/assets/54474809/cb6aa392-c075-4dd0-8c38-8233530ee35e)
yep it works fine on directx

**Comment by nem0** [comment]
OpenGL renderer is getting removed.
