### ISSUE TITLE
Windows crash when closing Lumix Studio

### ISSUE THREAD

**Issue by RednibCoding** [nem0/LumixEngine#1506]
When closing the project browser or lumix studio, the program crashes:
ASSERT is triggered in Allocator::deallocate at debug.cpp line 465.

Stacktrace:
```
studio.exe!Lumix::debug::Allocator::deallocate(void * user_ptr) Line 465
	at C:\Users\mlb\Downloads\LumixEngine\src\core\win\debug.cpp(465)
studio.exe!Lumix::TagAllocator::deallocate(void * ptr) Line 90
	at C:\Users\mlb\Downloads\LumixEngine\src\core\arena_allocator.cpp(90)
studio.exe!Lumix::IAllocator::deleteObject<Lumix::StudioApp::IPlugin>(Lumix::StudioApp::IPlugin * ptr) Line 31
	at C:\Users\mlb\Downloads\LumixEngine\src\core\allocator.h(31)
studio.exe!Lumix::StudioAppImpl::onShutdown() Line 261
	at C:\Users\mlb\Downloads\LumixEngine\src\editor\studio_app.cpp(261)
studio.exe!Lumix::StudioAppImpl::run::__l2::<lambda_1>::operator()() Line 360
	at C:\Users\mlb\Downloads\LumixEngine\src\editor\studio_app.cpp(360)
studio.exe!Lumix::jobs::runLambda::__l3::<lambda_1>::operator()(void * arg) Line 46
	at C:\Users\mlb\Downloads\LumixEngine\src\core\job_system.h(46)
studio.exe!`Lumix::jobs::runLambda<`Lumix::StudioAppImpl::run'::`2'::<lambda_1>>'::`3'::<lambda_1>::<lambda_invoker_cdecl>(void * arg) Line 46
	at C:\Users\mlb\Downloads\LumixEngine\src\core\job_system.h(46)
studio.exe!Lumix::jobs::manage(void * data) Line 350
	at C:\Users\mlb\Downloads\LumixEngine\src\core\job_system.cpp(350)
[External Code]
```

Locals:
| **Field**              | **Value**                                                                                         |
|------------------------|---------------------------------------------------------------------------------------------------|
| this                   | studio.exe!0x00007ff726172e08 {m_source={m_small_allocations=0x0000021d43630000 "€\x1" m_free_lists=...} ...} |
| info                   | 0x0000021d3fcbb6e8 {previous=0x0000021d3f9f18f0 {previous=0x0000021d3fcbb6e0 {previous=0x0000021d3fcbbb3c {...} ...} ...} ...} |
| lumix_assert_b___      | true (204)                                                                                        |
| system_ptr             | 0x0000021d3fcb8878                                                                                |
| system_size            | 2324201230552                                                                                     |
| user: ptr              | 0x0000021d3fcbb718                                                                                |

**Comment by nem0** [comment]
c2a292e211af7b3fb47eb0369139bb800ed2b14d

**Comment by nem0** [comment]
Thanks, fixed
