### ISSUE TITLE
Android port

### ISSUE THREAD

**Issue by nem0** [nem0/LumixEngine#155]
- [ ] compile 3rd party libraries
- [ ] [audio](https://github.com/nem0/LumixEngine/tree/master/src/audio)
- [ ] [editor](https://github.com/nem0/LumixEngine/tree/master/src/editor/pc)
- [ ] [debug](https://github.com/nem0/LumixEngine/tree/master/src/engine/debug/pc)
- [ ] [core](https://github.com/nem0/LumixEngine/tree/master/src/engine/core/pc)
- [ ] [MT](https://github.com/nem0/LumixEngine/tree/master/src/engine/core/MT/pc)
- [ ] [FS](https://github.com/nem0/LumixEngine/tree/master/src/engine/core/FS/pc)
- [ ] [app](https://github.com/nem0/LumixEngine/blob/master/src/app/main.cpp)
- [ ] [studio](https://github.com/nem0/LumixEngine/blob/master/src/studio/main.cpp)
- [ ] Shaders and rendering

---
- [ ] Continuous Integration
- [ ] Docs

**Comment by kingofoz** [comment]
any update to this feature?

**Comment by nem0** [comment]
Sorry for not responding here, Github is not sending me emails with new comments :(
Android is a very low priority right now.
