### ISSUE TITLE
Cloth

### ISSUE THREAD

**Issue by nem0** [nem0/LumixEngine#362]

**Comment by nem0** [comment]
https://github.com/nem0/lumixengine/tree/cloth
https://www.youtube.com/watch?v=cbSdrnbJZDU

**Comment by nem0** [comment]
Cloth is no longer part of PhysX, NvCloth does not use prohibitive license :(

**Comment by mafiesto4** [comment]
:(

**Comment by nem0** [comment]
indeed, I will research some other open source cloth simulation libs

**Comment by mafiesto4** [comment]
Maybe PhysX 5 will change that but it looks like they got delay on release: https://news.developer.nvidia.com/announcing-nvidia-physx-sdk-5-0/
