### ISSUE TITLE
Renaming Entities

### ISSUE THREAD

**Issue by damien022** [nem0/LumixEngine#566]
In the editor, destroying then adding an entity means that the latter has the same name as the former. Also there seems to be limit in the name size of the entity,

**Comment by nem0** [comment]
I've fixed the issue with destroying and adding a07fa107aaa6a3ed858c0ac9e9f916e9566976b3.  

Entity name can be max 255 characters long. Is this the limit you mentioned?

**Comment by damien022** [comment]
actually when i was destroying an entity, the new entity created had the
same name as the old one, and when deleting the name it only allowed one
letter for the new name

**Comment by nem0** [comment]
Should be fixed now c7242a2f375ea3461bda8cff7e26f5a4faa73519 & a07fa107aaa6a3ed858c0ac9e9f916e9566976b3

**Comment by nem0** [comment]
I am closing this, it should be fixed. If not feel free to reopen.
