### ISSUE TITLE
Cross platform support (Linux, OS X)

### ISSUE THREAD

**Issue by clix9** [nem0/LumixEngine#586]
Does Lumix support non-Windows platforms such as OS X and Linux? I believe all of Lumix's dependencies (bgfx, PhysX, imgui) have cross platform support, but I've looked through some of the engine's source code, and there are parts that appear to be Windows only.

**Comment by nem0** [comment]
There is a git branch with some parts ported to OS X, however it is quite old. I do intend to port Lumix to other platforms, as you've already mentioned, all dependencies are chosen that way. Most of the Windows only functions are encapsulated in win platform-only files. The only thing that is not prepared for porting is the editor, but it should not be too hard to change that. Linux/OS X port does not have high priority right now, as there are more important features missing, however it will definitely be done sooner or later (sooner if I manage to find someone to port it :)
