### ISSUE TITLE
The app running very slow on windows 7 64 bit 

### ISSUE THREAD

**Issue by meiry** [nem0/LumixEngine#612]
i compiled and also run  your compilation and in windows the editor is very very slow 
in fact it unusable to use .

**Comment by nem0** [comment]
You can use the builtin profiler https://github.com/nem0/LumixEngine/wiki/Profiler to find out what is so slow.

**Comment by meiry** [comment]
I can't even run the app , i start it and its semi stack very sluggish

**Comment by nem0** [comment]
Can you see anything in the window or is it just dark? Also is there any *.log in the root of data?

**Comment by meiry** [comment]
i can see windows 
first the "Welcome to Lumix Studio " is shown.
i close it then i see this window .
![w1](https://cloud.githubusercontent.com/assets/1107316/11271945/034cf798-8ed2-11e5-9489-5537b71b1ebd.png)

this windows is slow and unmovable .. i mean very very sluggish
and all my pc get slow 
This is the error log:
```
Could not open shaders/debuglin.shdCould not open shaders/particle.shdCould not open shaders/editorob.shdCould not open shaders/screensp.shdCould not open shaders/compiled/imgui_imgui0_vs.shbCould not open shaders/compiled/imgui_imgui0_fs.shbCould not open shaders/compiled/blur_blur_v0_vs.shbCould not open shaders/compiled/blur_blur_v0_fs.shbCould not open shaders/compiled/blur_blur_h0_vs.shbCould not open shaders/compiled/blur_blur_h0_fs.shbCould not open shaders/compiled/sky_sky0_vs.shbCould not open shaders/compiled/sky_sky0_fs.shbCould not open shaders/compiled/ssao_ssao0_vs.shbCould not open shaders/compiled/ssao_ssao0_fs.shb

```

**Comment by nem0** [comment]
It seems all shaders except gui are not compiled for some strange reason. Please try following:

1. delete directory shaders/compiled
2. run shaders/shader_test.bat
3. check whether there are shaders/compiled/rigid_MAIN0_fs.shb and shaders/compiled/rigid_MAIN0_fs.shb.d
4. If files are there, try to run the editor

-----

The editor tries to make all compiled shaders up-to-date at startup, it may take a few seconds and the application is slow during this compilation. If everything is successfully compiled there should be 156 files in shaders/compiled. 

-----

You can eventually extract https://github.com/nem0/lumixengine_data/raw/master/shaders/compiled/compiled.zip in shaders/compiled to user precompiled shaders

**Comment by nem0** [comment]
Is this any better? There is one more thing you can try : disable SSAO (and possibly other things) in Scene View -> Pipeline -> SSAO checkbox

**Comment by marynate** [comment]
Personally I don't any performance issue, but do notice the editor it's quite GPU hungry.  Turn off pipeline features did help, but not as much as I expected. Is there any other graphic setting could be play with?

And I think it might help to put editor fps to lower value (<10) when it's in background.

**Comment by nem0** [comment]
It is indeed very strange that empty scene consumes so much resources. Most of the shaders ATM are pure prototypes without any optimizations, some of them even incorrect, Especially SSAO is very ineffective. 

All the checkboxes in Scene View -> Pipeline are just variables in pipelines/main.lua, you can change this file directly to tweak it further.

I've created an issue #650

**Comment by meiry** [comment]
@nem0 
yes its much better when loading the basic scene
