### ISSUE TITLE
Only one script's "update" function been called

### ISSUE THREAD

**Issue by marynate** [nem0/LumixEngine#613]
How to reproduce:
```
1. open "main.unv"
2. assign a new lua script with "update" function to an entity
3. start game mode, notice only the new added lua script's "update" function been called.
```

**Comment by nem0** [comment]
At the moment this works as designed. I wanted to have only one update function which can "update" other entities on its own. However it is probably not the most user-friendly solution so I will change it.

**Comment by nem0** [comment]
Scripts are now properly sandboxed - https://github.com/nem0/LumixEngine/wiki/Lua-scripting

**Comment by marynate** [comment]
Cool! Just tested and it works as expected. Thanks!

Btw, how 2 lua script components (belong to 2 entities) supposed to communicate with each other?

**Comment by nem0** [comment]
Right now all data are sandboxed, it means each component has its own _ENV table, however they shared global table _G, which can be used for inter-component communication

Example:

script1.lua
```
...
_G.some_value = 4
...
```

script2.lua
```
...
if _G.some_value == 4 then foo() end
...
```

It would be possible to create function to return _ENV table of some component, however it feels like   a hack.

**Comment by marynate** [comment]
Thanks @nem0!
I'm not quite familiar with lua, but do you think it's a good idea to have some kind of event system for 2 lua component talk to each other? (I got the bad feeling when every lua script component start putting data into global table)

**Comment by nem0** [comment]
It is indeed not a good idea to use global table extensively. On the other hand some generic event system based on observer pattern or something different may be even worse. Third option is to use the function to get _ENV of some other component and use it directly. Anyway it is possible to have any of these systems:

```
-- option 1 - global table
_G.some_pos[x] = {1, 2, 3}
-- option 2 - event_system is implemented in lua
_G.event_system:emit({type=MOVE, pos={1,2,3}})
-- option 3 - getting environment
local env = API_getEnvironment(entityX) -- this function does not exists right now
env.setPosition({1, 2, 3})
```
