### ISSUE TITLE
Text based scene format

### ISSUE THREAD

**Issue by marynate** [nem0/LumixEngine#649]
While binary scene format are good for packaged game, text based format has some advantage when editing like git friendly, more easy to migrate/reconstruct to newer version.

btw, @nem0, curious how you manage to migrate the universe file each time to newer version?

**Comment by nem0** [comment]
I used to have a text based format, however it became too slow to load so I dropped it. Binary loads very fast (even big maps in 1/10s of seconds) and text based format  was way to slow (10s of seconds worst case). I have a very bad experience with text based resources from one of my previous jobs, when users damaged them several times each day using SVN. What is more to support both binary and text based format complicates code (either virtual methods, templates, duplicate code, ...)

To migrate I usually do something [like this](https://github.com/nem0/LumixEngine/commit/7a0965cde6bcb86e39cb22750787c9f1c03e3075#diff-5b4f2be9192822635353156224b4541dR334) so latest executable can automatically load older versions. However sometimes if the change is too big I create a temporary tool to migrate.

**Comment by marynate** [comment]
Personally I would like binary scene format for runtime game, and text format for scene editing (all other resources should stay binary), but it probably not worth the effort to maintain 2 format serializer like you said. 

But while the scene/plugin format been constant changing, the migration problem might still need to be deal with sooner or later. Maybe a dedicated scene migration tool?

**Comment by nem0** [comment]
Well, so far I had been neglecting the migration issue because I do not know about anybody seriously using the engine except me. But since more and more people use it from now on I will handle versions properly.
