### ISSUE TITLE
2D support

### ISSUE THREAD

**Issue by marynate** [nem0/LumixEngine#651]
Wondering what's the plan on 2D support in LumixEngine?

**Comment by nem0** [comment]
Everything that is done is aimed for 3D. It is possible to have 2D plugin as long as it does not affect the core.

I do not plan to plan to implement 2D myself, I think for 2D game 2D only engine should be used. There is plenty of space for specific optimizations and tools in 2D. Of course it is possible to have support for 2D in the engine, like it is in e.g. unity, but I've always found their 2D not sufficient (at least in the older versions, I do not know about the new ones). 

What is more even if I wanted to have 2D support, I do not have resources for that.

**Comment by marynate** [comment]
I see, that's totally understandable. Thanks for your answer. And btw, great job so far!
