### ISSUE TITLE
Any plans for making this cool engine run on OSX?

### ISSUE THREAD

**Issue by dumganhar** [nem0/LumixEngine#807]
This is an awesome game engine. 👍 :)

**Comment by nem0** [comment]
There is an issue #15, also there is also a very old [branch](https://github.com/nem0/LumixEngine/tree/osx_port) with some stuff already ported. It will eventually happen but it's not my priority at the moment.

**Comment by dumganhar** [comment]
Thanks. I'll check out that branch.
