### ISSUE TITLE
If you have the shader panel docked, the right click context menu for the shader panel works for every panel.

### ISSUE THREAD

**Issue by antonyjones67** [nem0/LumixEngine#861]
It seems like the context menu is not verifying what panel it is clicked in.

**Comment by nem0** [comment]
Thanks for the report. To be honest Shader editor was not maintained for some time, I need to clean it up a bit.

**Comment by antonyjones67** [comment]
Cool. I think this might be true for keyboard commands. Do you think this is just a Shader Editor problem? Or does it apply to docked panels in general?

**Comment by nem0** [comment]
It is not related to the docking system itself. This is the only popup done like this:

```cpp
	if(ImGui::IsMouseClicked(1))
	{
		ImGui::OpenPopup("context_menu");
	}
```

while others are bind to a specific button

```cpp
	if (ImGui::Button(Lumix::StaticString<30>("...###br", str_id)))
	{
		ImGui::OpenPopup(popup_name);
	}
```

**Comment by antonyjones67** [comment]
oh wow that was easy. :) nice

**Comment by antonyjones67** [comment]
thank you.

**Comment by nem0** [comment]
Things are usually easy with imgui

**Comment by antonyjones67** [comment]
So cool. :)
