### ISSUE TITLE
Can't type in a new shader path name into material properties shader path name.

### ISSUE THREAD

**Issue by antonyjones67** [nem0/LumixEngine#862]
It won't let you type the name in. I think it may be trying to update something. Which causes the file path name property to lose focus. If you use the [...] button it works just fine.

**Comment by nem0** [comment]
This turned out to be quite a conceptual problem. When you change one character in a path it will try to load the new path, displaying "Loading" for a frame or two, which causes the lost focus. So I changed the path to read-only ("..." still works) since it seems how other engines do it.
