### ISSUE TITLE
Labels waste too much space

### ISSUE THREAD

**Issue by nem0** [nem0/LumixEngine#867]
![unused_realestate](https://cloud.githubusercontent.com/assets/153526/15746225/f565c9ae-28d5-11e6-9052-b42325ffa6cc.png)

**Comment by PeaceSells50** [comment]
Hey Mikulas, can we just get rid of the labels entirely. Maybe use tooltips to show what each pane does?

**Comment by nem0** [comment]
Is there any editor which do that? I think it might be too confusing.

**Comment by PeaceSells50** [comment]
can we put the labels in between the controls?

**Comment by PeaceSells50** [comment]
sorry about this. it is not a high priority thing. :)
