### ISSUE TITLE
studio.exe require vs14 runtime to run  

### ISSUE THREAD

**Issue by codz01** [nem0/LumixEngine#879]
Hi nem0 
can you rebuild the editor with static linking , vs14 runtime library is a hell of dll's
![untitled](https://cloud.githubusercontent.com/assets/10813427/15912298/4c9f141a-2dcb-11e6-8614-fc5261e939ed.png)

many thanks

**Comment by nem0** [comment]
Sure I will rebuild it, but if you don't mind me asking, is there any problem with installing redistributable?

**Comment by codz01** [comment]
it's the laziness ;) , or maybe i hate vs , i already installed redistributable of 2008 , 2010 , 2012 , 2013

**Comment by nem0** [comment]
You are probably going to install it anyway one day because of some other app :) I will do it as soon as I finish a task I work on, hopefully in less than two hours.

**Comment by codz01** [comment]
thats one of many reason i use tdm-gcc instead .

**Comment by codz01** [comment]
thanks

**Comment by nem0** [comment]
Never heard of that, but since they have this on their webpage:
![tdm](https://cloud.githubusercontent.com/assets/153526/15912476/cfa4971e-2dd4-11e6-9d1f-d64620d445f7.png)
I am a bit sceptical.

**Comment by codz01** [comment]
vs has a very strong ide without doubt . but the policy of microsoft which i don't like , they forcing you to install thier new OS's in order to be able to install the newer VS

**Comment by nem0** [comment]
I have VS15 on Win7

**Comment by nem0** [comment]
BTW, do you want 64bit or 32bit?

**Comment by nem0** [comment]
Oh c..p, I have to recompile all the 3rd party libraries. I am sorry but I will probably not manage to do that today.

**Comment by codz01** [comment]
my windows is win7 32bits . ok i'll wait until you rebuild the editror .
btw , the editor really looks interesting . i wish all success for this project

**Comment by nem0** [comment]
It turns out it cannot be done, PhysX is compiled with dynamic runtime and runtimes can not be mixed, sorry.

**Comment by codz01** [comment]
its ok , i've installed msvc2015 redistributable
