### ISSUE TITLE
Feature request: Mesh painter

### ISSUE THREAD

**Issue by JimSEOW** [nem0/LumixEngine#880]
Got interested on Lumix Engine because of this link at Youtube that refers to LumixEngine.

Is it possible to add this feature?
https://www.youtube.com/watch?v=f0P1ZqO0zOk
https://www.youtube.com/watch?v=HA5dpKqn3j0

**Comment by nem0** [comment]
It's a standalone app using the docking system from Lumix, it's not related to Lumix in any other way. 

Maybe one day this will be implemented, but compared to other features this has extremely low priority.
