### ISSUE TITLE
After adding icons to main tool bar, icons are being highlighted in a strange way. See picture.

### ISSUE THREAD

**Issue by PeaceSells50** [nem0/LumixEngine#886]
![image](https://cloud.githubusercontent.com/assets/12586944/16029105/4deffb6e-31a3-11e6-81a6-33c1a616018a.png)

**Comment by PeaceSells50** [comment]
Hey Mikulus. This is the order I was hoping to have the icons in.

**Comment by nem0** [comment]
How would you like to hight the active icons?

**Comment by nem0** [comment]
The hightlight is not so important for windows, but it's necessary for translate/rotate, local/global, pivot/center
