### ISSUE TITLE
Replace instance of model A in world with another model B from Asset Browser.

### ISSUE THREAD

**Issue by PeaceSells50** [nem0/LumixEngine#890]
Optional:
1. Replace all instances of A.
2. Replace all selected instances of A.

**Comment by nem0** [comment]
I knew I should not have removed that :)

**Comment by nem0** [comment]
duplicate of #738

**Comment by nem0** [comment]
Note: it's also good to use https://github.com/nem0/LumixEngine/wiki/Entity-templates
