### ISSUE TITLE
Waypoint system for AI navigation.

### ISSUE THREAD

**Issue by PeaceSells50** [nem0/LumixEngine#894]

**Comment by nem0** [comment]
Could you elaborate more please? There is function ```navigate``` already in lua API. I am already using it together with entities with attached scripts to create a waypoint system.

**Comment by PeaceSells50** [comment]
My son just actually did some bird AI, using Waypoints in Unity. You can create Waypoints in the sky and then on the ground. So that you can get birds to circle and land. You can also test to see if the Avatar is at the Waypoint on the ground and choose to not go there.

**Comment by nem0** [comment]
Everything necessary to script this is done
