### ISSUE TITLE
Flocking. Crowd control.

### ISSUE THREAD

**Issue by PeaceSells50** [nem0/LumixEngine#896]
Will Detour do what we want?

**Comment by nem0** [comment]
It has some crowd system

**Comment by PeaceSells50** [comment]
I wasn't thinking so much for birds. But animals running around in heards on the ground. Some kind of AI avoidance. Bird flocking can actually be done fairly cheaply if they all follow the same path.

**Comment by nem0** [comment]
Using detour crowd now
