### ISSUE TITLE
Assert when trying to move the shader editor window when it is in a bad state.

### ISSUE THREAD

**Issue by PeaceSells50** [nem0/LumixEngine#909]
studio.ini
https://www.dropbox.com/s/lzmyu4mfawmfihx/studio.ini?dl=0

use this ini file then click view shader editor. the shader editor will overlay the main window in a weird way.

imgui.cpp line 2135: IM_ASSERT(g.MovedWindow->RootWindow->MoveID == g.MovedWindowMoveId);

Callstack:
>	engine.dll!ImGui::NewFrame() Line 2135	C++
 	editor.dll!StudioAppImpl::guiBeginFrame() Line 260	C++
 	editor.dll!StudioAppImpl::update() Line 339	C++
 	editor.dll!StudioAppImpl::run() Line 1808	C++
 	studio.exe!WinMain(void * __formal, void * __formal, char * __formal, int __formal) Line 9	C++
 	[External Code]

**Comment by nem0** [comment]
Hi this was fixed in 3b9c08fa25712a8be5c0b92477a54d9bff7d413b, did you try some older version?
