### ISSUE TITLE
Actor properties and an Actor Properties Panel.

### ISSUE THREAD

**Issue by PeaceSells50** [nem0/LumixEngine#919]
![image](https://cloud.githubusercontent.com/assets/12586944/16541707/e96d3e0a-4047-11e6-9d57-dc06d00dfd16.png)

**Comment by nem0** [comment]
Could you provide some more information please? I do not understand what this issue is about.

**Comment by PeaceSells50** [comment]
I'm thinking maybe this may not be necessary. I believe there already is a mechanism in code for adding actor properties and you can get to them through the property panel. I was thinking of something like a blackboard in unreal. So that the users have a user interface for adding actor related metadata.

**Comment by PeaceSells50** [comment]
I guess in Unity they mostly add them through script.

**Comment by nem0** [comment]
Yes, the way how they do it in Unity through script is possible in Lumix too.
https://github.com/nem0/LumixEngine/blob/master/src/lua_script/lua_script_system.cpp#L116

**Comment by nem0** [comment]
You can see some properties in the begining of https://github.com/nem0/lumixengine_data/blob/master/scripts/player.lua

**Comment by PeaceSells50** [comment]
Yeah I believe this handles most situations Does it seem complicated to have to refer to a script to add metadata? What if I want to add actor properties for things like AI or AnimationTrees. And not necessarily have to create a lua script for it.

**Comment by PeaceSells50** [comment]
I guess it depends on how the AI or AnimationTrees are implemented.
