### ISSUE TITLE
Event/Callback system. Possibly using Fast Delegates.

### ISSUE THREAD

**Issue by PeaceSells50** [nem0/LumixEngine#920]

**Comment by nem0** [comment]
https://github.com/nem0/LumixEngine/blob/master/src/engine/delegate.h

**Comment by PeaceSells50** [comment]
Yes. I did see that in there. But I mean something that you set up with a macro. For instance setting up entities to receive events using callbacks. Like OnCollide() or something like that.

**Comment by PeaceSells50** [comment]
I probably did not describe it very well, but I mean and Entity based event system.

**Comment by nem0** [comment]
It's done like this:
https://github.com/nem0/LumixEngine/blob/master/src/engine/universe/universe.h#L65
https://github.com/nem0/LumixEngine/blob/master/src/renderer/render_scene.cpp#L217

**Comment by PeaceSells50** [comment]
Oh yeah. I forgot about this. I have seen this before. I am very sorry about this issue.

**Comment by nem0** [comment]
No problem, FYI there also use to be other system for messaging https://github.com/nem0/LumixEngine/blob/547e124947350a639887a4ac15dd23f389ea1fbc/src/core/event_manager.h
