### ISSUE TITLE
Skinning bug with FBX file.

### ISSUE THREAD

**Issue by PeaceSells50** [nem0/LumixEngine#936]
Lumix Engine:

![image](https://cloud.githubusercontent.com/assets/12586944/16678285/dc1e3aae-449a-11e6-8163-e2432a8a3127.png)

Unreal Engine

![image](https://cloud.githubusercontent.com/assets/12586944/16678288/eaf15656-449a-11e6-8a3f-cb3c2d725476.png)

**Comment by PeaceSells50** [comment]
Here is the FBX file. https://www.dropbox.com/home?preview=CartoonMannequin.zip

**Comment by nem0** [comment]
This is how it looks in my case.
![image](https://cloud.githubusercontent.com/assets/153526/16681192/82b0ce7e-44f3-11e6-8fc3-2839d4f05573.png)

I can see there are error in log in your screenshot, are they related to this in any way?

**Comment by nem0** [comment]
I managed to reproduce it (I had to scale the mesh during import) and I've fixed it

**Comment by PeaceSells50** [comment]
Cool thank you. The errors are irrelevant. Shader related.
