### ISSUE TITLE
How to setup on/off imgui-dock titlebar close button?

### ISSUE THREAD

**Issue by zhouxs1023** [nem0/LumixEngine#945]
if i want to close dock widgets titlebar close button for my  scence view , how  should I setup ?

**Comment by nem0** [comment]
Scene view is not closable by design. Why do you need this?

**Comment by zhouxs1023** [comment]
I use begindock/enddock generated dock with close button,but  I want to one dock widget without  close button,How  should I do?

**Comment by nem0** [comment]
Ah, I am sorry I misunderstood the first time. You can use nullptr as second parater to BeginDock to disable the close button.
