### ISSUE TITLE
Can you help me explain opened or *opened dock.opened about dock?

### ISSUE THREAD

**Issue by zhouxs1023** [nem0/LumixEngine#948]
in dock widget, opened status  confused me,pls help me explain them for me.
if (!dock.opened && (!opened || *opened)) tryDockToStoredLocation(dock);
		dock.last_frame = ImGui::GetFrameCount();

**Comment by nem0** [comment]
if the parameter is null, there is no close button
if it's not null, there is a close button and the parameter points to a boolean whentere the dock is opened or closed
