### ISSUE TITLE
PBR

### ISSUE THREAD

**Issue by luchete80** [nem0/LumixEngine#962]
Hi, i began to play around with PBR, based on Urho3D BRDF, for now just understanding Lumix. Thanks for your work and i hope to help this project if something comes out of my branch.

Links: [https://github.com/luchete80/lumixengine_data.git](url)

Setting up scene: [https://www.facebook.com/Leda-Games-674096542694457/](url)

**Comment by nem0** [comment]
Hi, that's great. @dragonCASTjosh has similar plans. You can see some more info https://gitter.im/nem0/LumixEngine. 
If you have any questions or anything I can help you with, just let me know.

**Comment by luchete80** [comment]
Thank you very much!

**Comment by dragonCASTjosh** [comment]
I can help with porting

**Comment by luchete80** [comment]
Great!! very impressive you work with Urho3D

**Comment by dragonCASTjosh** [comment]
Thanks :) if you set up passing the texture to the shader I can set up the BRDF fairly easy. The ibl should be simple but I was considering setting up filtering in editor.

Advanced features like area lights are R&D at the moment.

also @nem0 what's your stance on quality vs performance.

**Comment by dragonCASTjosh** [comment]
I highly recommend burley diffuse as it's more physically grounded and the results are noticeable :)

**Comment by dragonCASTjosh** [comment]
I'll look into your branch more tomorrow and pr as needed

**Comment by nem0** [comment]
> also @nem0 what's your stance on quality vs performance.
I prefer for users to have a choice, e.g. as a define in shader code.

**Comment by dragonCASTjosh** [comment]
I mean for things such are IBL where they require largely varying implementation such as loading additional texture and/or filtering the IBL

**Comment by nem0** [comment]
Of course IBL is not possible without loading additional texture, there is no question in that.

**Comment by nem0** [comment]
BTW how do you want to apply IBL texture?

**Comment by dragonCASTjosh** [comment]
In urho I did ibl without loading addition pre made textures by using a lower quality mobile approch

**Comment by dragonCASTjosh** [comment]
What you mean

**Comment by dragonCASTjosh** [comment]
IBL should be done on a separate pass to surface shading and the results added in to the main shading prior to gamma correction

**Comment by luchete80** [comment]
I was reading something from disney and it seems burley is very noticeable against oren-nayar. 
I was thinking also burley for diffuse and some like Cook Torrance specular or similar to frostbite.

Take your time to look into my branch since i forked recently yesterday and they are only ideas :) !!!

**Comment by dragonCASTjosh** [comment]
For Urho I experimented alot on the brdf and found the best results. Turned out to be the same findings as frostbite :)

**Comment by nem0** [comment]
> In urho I did ibl without loading addition pre made textures by using a lower quality mobile approch

in that case I prefer quality

**Comment by dragonCASTjosh** [comment]
Render pipelines importance samples approach may be best then. Still doesn't need the NdotL vs roughness retire but results are just as good if not slightly better and performance around the same

**Comment by dragonCASTjosh** [comment]
I left the importance sampled code in urho incase anyone wants to. Feel free to experiment

**Comment by dragonCASTjosh** [comment]
I was supposed to put NdotL vs Roughness texture, same I can't edit messages on mobile

**Comment by meshula** [comment]
Simply adding the input from IBL in a separate pass from direct illumination will not be energy conserving, and the result will be quite noticeable if you don't have some way to account for it. It's probably a good idea to develop a "good" and "optimized" renderer side by side to be sure "optimized" is doing the right thing.

**Comment by nem0** [comment]
related #903

**Comment by luchete80** [comment]
Thanks @nem0! I will check cfmt

**Comment by luchete80** [comment]
Hi guys, created roughness and metalness to material class. SEVERAL things to correct, but just for fun:
![20160804_3](https://cloud.githubusercontent.com/assets/13024214/17422818/d2b1feb8-5a8b-11e6-8c24-11ab98c4f5a1.PNG)
![20160804_4](https://cloud.githubusercontent.com/assets/13024214/17422821/d9ce92ec-5a8b-11e6-9c49-e19295ead06f.PNG)

**Comment by luchete80** [comment]
Also i could combine these with maps, but for now only that, also checking for ibl later on

**Comment by luchete80** [comment]
passing it to deferred now

**Comment by nem0** [comment]
Nice. Good job.

**Comment by nem0** [comment]
@luchete80 FYI I changed the structure of shaders, they are in pipelines directory and they can be in a subdirectory, so they can be organized better

**Comment by luchete80** [comment]
Thanks @nem0
