### ISSUE TITLE
Time Line GUI - for Animation Event Panel

### ISSUE THREAD

**Issue by PeaceSells50** [nem0/LumixEngine#963]
![image](https://cloud.githubusercontent.com/assets/12586944/17444164/cd089754-5afb-11e6-9e9c-fcc9c5396ac4.png)

**Comment by PeaceSells50** [comment]
The orange lines need to be slide able. They represent ranges. And should be scalable.

**Comment by nem0** [comment]
blocks #770

**Comment by nem0** [comment]
![image](https://cloud.githubusercontent.com/assets/153526/17481388/3f356356-5d7d-11e6-82df-de57409eda85.png)

**Comment by nem0** [comment]
![timeline](https://cloud.githubusercontent.com/assets/153526/17481509/e0a2696e-5d7d-11e6-87a0-e11b489f110d.gif)

**Comment by nem0** [comment]
You can find it in timeline_gui branch

**Comment by PeaceSells50** [comment]
OMGosh! You are soooo fast. You scare me! Thank you for this. Now I can add Animation Events. :) Unless I am taking work away from you that you would rather do. Let me know. :)

**Comment by nem0** [comment]
It's not me, it's thanks to imgui :) If you need anything else just let me know and I will fit it in my plans.
