### ISSUE TITLE
Error deserializing universe from app

### ISSUE THREAD

**Issue by luchete80** [nem0/LumixEngine#968]
I'm copying an existing universe into another one with another name, updating this name in startup.lua, and running app, or even building a new one making it similar to an existing working one (the originals player.unv, terrain.uv works great). 

But when running app it seems to throw an JSON deserializer (error.log):
"Missing plugin guiFailed to deserialize universe"
I probably could be doing something wrong due i'm learning to use it (i've tried with newer engine versions or data but i've got another messages).

I'm currently working with v0.26 engine and data from:
https://github.com/nem0/lumixengine_data/commit/e4accf59b8e7146bcba7f8eccff00299907aea14

**Comment by nem0** [comment]
Should be fixed now, just checkout the latest source code

**Comment by luchete80** [comment]
great man, you're fast
