### ISSUE TITLE
Failed to create vertex shader (dx9 and opengl 3.3) on low-end gpu

### ISSUE THREAD

**Issue by luchete80** [nem0/LumixEngine#969]
OpenGL 3.3, dx9 (vertex shader 4 version) crashed with bgfx message: "failed to create shader", last shader compiled are billboard_POINT_LIGHT9_fs for dx9 and pbr_DEFERRED0_vs for opengl. 

I've discarded a bgfx problem by running another bgfx application like https://eheitzresearch.wordpress.com/415-2/ and it runs ok for both opengl and dx9.

Maybe it does not run for these api versions.

**Comment by nem0** [comment]
[sm 5 / gl 1.40](https://github.com/nem0/LumixEngine/blob/master/src/renderer/editor/shader_compiler.cpp#L382) are required. You can change it to something lower but you would have to replace the default shaders.

**Comment by luchete80** [comment]
thanks you!

**Comment by nem0** [comment]
I tried to change it to sm4 and it seems it works without any fixes in shaders

**Comment by nem0** [comment]
581796a2cd2e3e3f6c4b4a617cdff148d53bc3f0 this caused that an error message from shader compiler was not displayed if it was too long

**Comment by luchete80** [comment]
Thanks to you!
