### ISSUE TITLE
GUI disappears with too many instances rendered

### ISSUE THREAD

**Issue by nem0** [nem0/LumixEngine#971]
set grass distance to 250 and density to 25 and observe that gui disappears

**Comment by luchete80** [comment]
I`ve seen this behavior loading a gta mod car mesh with different damaged configurations, when loading, gui dissapeared for some angles but back to normal for some others. I will put the mesh on my branch if is still some where

**Comment by luchete80** [comment]
I`ve seen this behavior loading a gta mod car mesh with different damaged configurations, when loading, gui dissapeared for some angles but back to normal for some others. I will put the mesh on my branch if is still some where

**Comment by nem0** [comment]
Do not worry. I know exactly what is the cause. There is a limited buffer for instances and transient stuff (which gui and grass are) and since grass depletes the buffer, gui is not rendered.

**Comment by luchete80** [comment]
Great!!good to know you`ve found the cause
