### ISSUE TITLE
Create entity menu items

### ISSUE THREAD

**Issue by luchete80** [nem0/LumixEngine#973]
Combining latest dinamic linked binaries with data, the create entity menu item is showing only some entities in last binaries.
This does not occur with data static binaries.
![snapshot](https://cloud.githubusercontent.com/assets/13024214/17683975/fa1bba2a-632d-11e6-9471-cd1a179d06c2.PNG)
Do you know what is happening?

**Comment by nem0** [comment]
It's not just some but all of them, they are just group together. It's correct in the screenshot. However it should be the same in both static and dynamic build. Did you try to fully rebuild the static solution?

**Comment by luchete80** [comment]
Oh man, sorry for that. I think it was late and i was like burned out yesterday, i did not see mesh in Render group. I see them in both static and dynamic. Thanks. By the way, very handy the groups.
A question, any time i import an asset have to restart studio in order to see the mesh in models? Could be a refresh of this folder if i add something?
Thanks!

**Comment by nem0** [comment]
> any time i import an asset do i have to restart studio in order to see the mesh in models
It should be automatically detected as long as the feature is turned on 
![image](https://cloud.githubusercontent.com/assets/153526/17697582/f0da084e-63b5-11e6-933e-e4d2ab7cafae.png)

**Comment by luchete80** [comment]
great, thanks!
