### ISSUE TITLE
Crash callstach when creating new mesh

### ISSUE THREAD

**Issue by luchete80** [nem0/LumixEngine#976]
Since las few commits with mi pbr and clone master branches i'm seeing the following when created mesh:
![show_gizmo](https://cloud.githubusercontent.com/assets/13024214/17869199/9843efba-6888-11e6-9b9f-f1ce674186f5.PNG)

**Comment by nem0** [comment]
Hmm, the callstack makes no sense, I can't see any way it can crash there. 
Do you have your own executables or do you use the prebuilt ones?
Can I simply reproduce this if I download your fork?

**Comment by luchete80** [comment]
@nem0, i reset the branch, reload changes, recompile binaries (dynamic linked), and its works fine for pbr branch. However, by now, with the originals data studio binaries i cannot open a universe since studio shows an empty call stack and log says it cannot open shaders.
Do not worry, i will be working with both bullet and pbr branches whose binaries are compiled by me, bypassing the originals from data. 
Thanks for always being there!
