### ISSUE TITLE
Compiling shader when itinializing

### ISSUE THREAD

**Issue by luchete80** [nem0/LumixEngine#977]
Is a way to not compile all shaders every time lumix studio is initialized? I think this slows down significantly the times for developing. Or at least can this be selectable by the user ?

**Comment by nem0** [comment]
Only changed shaders are compiled. If there is not change and shaders are recompiling anyway you might wanna try to delete pipelines/compiled, it gets broken sometimes when you change shaders a lot.

**Comment by luchete80** [comment]
Great, thanks!
