### ISSUE TITLE
Landscape Auto Material

### ISSUE THREAD

**Issue by PeaceSells50** [nem0/LumixEngine#988]
https://www.youtube.com/watch?v=wkypCxc2Mzg

A really clever way to texture map and build terrain.

**Comment by nem0** [comment]
Could you please describe what features are you missing?

**Comment by PeaceSells50** [comment]
You could probably create this easily. It is a shader that takes multiple textures as input. It looks at the slope of the terrain and it will automatically apply the texture based on the slope of the terrain. So when you use your terrain deformation tools textures will automatically be choosen for you. It is a fun video to watch. Procedural modeling really is an amazing time savings for an artist.

**Comment by nem0** [comment]
In that case it's just a shader, no source code changes are necessary

**Comment by PeaceSells50** [comment]
Oh this goes in your other Git repository. Sorry.
