### ISSUE TITLE
Grass "physics"

### ISSUE THREAD

**Issue by nem0** [nem0/LumixEngine#992]
Grass should be able to react to other entities - moving animals, dead bodies

**Comment by Alan-FGR** [comment]
This could be done in the vertex shader: pass say 32 float4s containing position and radius to the shader from the 32 nearest things (could be say approximations of limbs and such) that should affect the grass and push the vertices away from them. I believe that's how a lot of games solved that, and the amount of data to be passed would be minimal. It's especially useful if you're maintaining sparse VBOs for the grass and if you do other animation in the VS anyway, so you could use the same 'weight' that's used for say wind animation so you don't move the vertices that aren't supposed to.

**Comment by nem0** [comment]
That's exactly how I plan to do it
